# Generated by Django 6.0.2 on 2026-02-26 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ru', models.CharField(max_length=120)),
                ('name_ky', models.CharField(max_length=120)),
                ('website', models.URLField(blank=True)),
                ('support_phone', models.CharField(blank=True, max_length=80)),
                ('hq_address_en', models.CharField(blank=True, max_length=220)),
                ('hq_address_ru', models.CharField(blank=True, max_length=220)),
                ('hq_address_ky', models.CharField(blank=True, max_length=220)),
                ('about_en', models.TextField(blank=True)),
                ('about_ru', models.TextField(blank=True)),
                ('about_ky', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=120)),
                ('rate', models.FloatField()),
                ('months', models.IntegerField()),
                ('max_amount', models.IntegerField(default=200000)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=120)),
                ('amount', models.IntegerField()),
                ('months', models.IntegerField()),
                ('rate', models.FloatField(default=0)),
                ('monthly_payment', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=120)),
                ('address_en', models.CharField(max_length=220)),
                ('address_ru', models.CharField(max_length=220)),
                ('address_ky', models.CharField(max_length=220)),
                ('hours', models.CharField(blank=True, max_length=120)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='loans.bank')),
            ],
        ),
        migrations.CreateModel(
            name='CreditHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=120)),
                ('original_amount', models.IntegerField(default=0)),
                ('opened_at', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ontime', 'On time'), ('late', 'Late'), ('default', 'Default')], default='ontime', max_length=20)),
                ('late_payments', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('mortgage', 'Mortgage'), ('consumer', 'Consumer'), ('auto', 'Auto'), ('business', 'Business'), ('education', 'Education')], default='consumer', max_length=20)),
                ('title_en', models.CharField(max_length=160)),
                ('title_ru', models.CharField(max_length=160)),
                ('title_ky', models.CharField(max_length=160)),
                ('min_amount', models.IntegerField(default=0)),
                ('max_amount', models.IntegerField(default=0)),
                ('min_months', models.IntegerField(default=3)),
                ('max_months', models.IntegerField(default=60)),
                ('rate_from', models.FloatField(default=0)),
                ('rate_to', models.FloatField(default=0)),
                ('collateral', models.CharField(blank=True, max_length=120)),
                ('is_islamic', models.BooleanField(default=False)),
                ('desc_en', models.TextField(blank=True)),
                ('desc_ru', models.TextField(blank=True)),
                ('desc_ky', models.TextField(blank=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loans.bank')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('months', models.IntegerField()),
                ('monthly_payment', models.IntegerField(default=0)),
                ('decision_status', models.CharField(choices=[('approved', 'Approved'), ('alternative', 'Alternative'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('approval_probability', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('mortgage', 'Mortgage'), ('consumer', 'Consumer'), ('auto', 'Auto'), ('business', 'Business'), ('education', 'Education')], default='consumer', max_length=20)),
                ('amount', models.IntegerField()),
                ('months', models.IntegerField()),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
